import{a as v,i as c,S as L}from"./assets/vendor-BjRz3xa9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();async function g(t,r=1){const i="49456082-a9826f5e30a55e93368b2873a",a="https://pixabay.com/api/",s={key:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{const o=await v.get(`${a}`,{params:s});return{images:o.data.hits,totalHits:o.data.totalHits}}catch(o){throw console.error("Error fetching images",o),o}}let p;function m(t,r,i=!1){if(i||(r.innerHTML=""),t.length===0){c.error({position:"topRight",backgroundColor:" #ef4040",messageColor:"#ffffff",message:"Sorry, there are no images matching your search query. Please try again!"});return}const a=t.map(e=>`<li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
            <img src="${e.webformatURL}" alt="${e.tags}" />
          </a>
          <div class="image-info">
            <p><span class="label">Likes:</span>${e.likes}</p>
            <p><span class="label">Views:</span>${e.views}</p>
            <p><span class="label">Comments:</span>${e.comments}</p>
            <p><span class="label">Downloads:</span>${e.downloads}</p>
          </div>
        </li>
    `).join("");r.insertAdjacentHTML("beforeend",a),p?p.refresh():p=new L(".gallery-link",{captionsData:"alt",captionDelay:250})}const y=document.querySelector(".form"),h=document.querySelector(".gallery"),n=document.querySelector(".loader"),f=document.querySelector(".load-btn");let l=1,d=0,u="";const E=15;n.style.visibility="hidden";f.classList.add("visually-hidden");y.addEventListener("submit",w);f.addEventListener("click",P);function b(){const t=document.querySelector(".gallery-item");if(t){const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}async function w(t){if(t.preventDefault(),l=1,d=0,u=t.target.elements["search-text"].value.trim(),!u){c.error({title:"Error!",position:"topRight",backgroundColor:" #ef4040",messageColor:"#ffffff",message:"Please, enter a search query!"});return}n.style.visibility="visible";try{const{images:r,totalHits:i}=await g(u,l);m(r,h),n.style.visibility="hidden",d=Math.ceil(i/E),d>l?f.classList.remove("visually-hidden"):f.classList.add("visually-hidden"),b()}catch{c.error({title:"Error!",position:"topRight",backgroundColor:" #ef4040",messageColor:"#ffffff",message:"Error fetching images"}),n.style.visibility="hidden"}finally{y.reset()}}async function P(){l+=1;try{const{images:t}=await g(u,l);m(t,h,!0),n.style.visibility="hidden",l>=d&&(f.classList.add("visually-hidden"),c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})),b()}catch{c.error({title:"Error!",position:"topRight",backgroundColor:" #ef4040",messageColor:"#ffffff",message:"Error fetching images"}),n.style.visibility="hidden"}}
//# sourceMappingURL=index.js.map
